#!/bin/bash

# Author: Vivek Ramachandran
# Contributor: Giovanny Ortegon

echo '[+] Assembly with NASM...'
nasm -felf $1.asm -o obj.o

echo '[+] Linking...'
ld -m elf_i386 obj.o -o main

echo '[+] Done!!'
